timeout: 5
default_entry: NasuaOS 64-bit
interface_branding: NasuaOS

interface_help_hidden: yes

# Debug
verbose: yes

wallpaper: boot():/boot/assets/images/background.png
wallpaper_style: stretched

/NasuaOS 32-bit
    protocol: multiboot
    path: boot():/boot/kernel_32bit
    comment: 32-bit kernel

/NasuaOS 64-bit
    protocol: limine
    path: boot():/boot/kernel_64bit
    comment: 64-bit kernel