#! /bin/sh

set -e

srcdir="$(dirname "$0")"
test -z "$srcdir" && srcdir=.

cd "$srcdir"

# Usuń stare zależności, jeśli istnieją w głównym katalogu
rm -rf freestanding-c-hdrs freestanding-cxx-hdrs cc-runtime limine-protocol .deps-obtained

echo "Kopiowanie lokalnych zależności z folderu confile..."

# Kopiowanie folderów z confile do głównego katalogu projektu
cp -r ../confile/freestanding-c-hdrs ./
cp -r ../confile/freestanding-cxx-hdrs ./
cp -r ../confile/cc-runtime ./
cp -r ../confile/limine-protocol ./

# Utworzenie wymaganego przez Makefile pliku-flagi
touch .deps-obtained

printf "\nDependencies obtained successfully from local confile directory.\n"
