#!/bin/sh

set -e

srcdir="$(dirname "$0")"
test -z "$srcdir" && srcdir=.

cd "$srcdir"

rm -f .deps-obtained

rm -rf temp-files

git clone --depth 1 \
    --branch main \
    https://github.com/Szatakis/NasuaOS-Bootloader.git \
    temp-files

cp -r temp-files/freestanding-c-hdrs .
cp -r temp-files/freestanding-cxx-hdrs .
cp -r temp-files/cc-runtime .
cp -r temp-files/limine-protocol .

rm -rf temp-files

touch .deps-obtained

printf "\nDependencies obtained successfully.\n"