name: Build NasuaOS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            cmake \
            ninja-build \
            nasm \
            xorriso

      - name: Build ISO
        run: |
          make all

      - name: Find ISO
        run: |
          find . -name "*.iso"

      - name: Upload ISO to iso branch
        run: |
          mkdir iso-upload
          cp *.iso iso-upload/

          cd iso-upload

          git init
          git checkout -b iso

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add .
          git commit -m "Update NasuaOS ISO"

          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git push --force origin iso